### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by imwints** [romner-set/btop-gpu#1]
Can you explain to me how this works and what the user is expected to do to enable GPU support? I just tried to compile it, it doesn't work with clang btw, and I cannot get a window to show when pressing 5. The gpu0 name is empty in the settings. I might be expecting to much cause this is WIP. What is expected to work currently?

You asked for logs, here it is:
```
2023/07/19 (16:59:27) | ===> btop++ v.1.2.13
2023/07/19 (16:59:27) | DEBUG: Starting in DEBUG mode!
2023/07/19 (16:59:27) | INFO: Logger set to DEBUG
2023/07/19 (16:59:27) | DEBUG: Using locale en_US.utf8
2023/07/19 (16:59:27) | INFO: Running on /dev/pts/4
2023/07/19 (16:59:27) | INFO: Failed to load librocm_smi64.so, AMD GPUs will not be detected: librocm_smi64.so: cannot open shared object file: No such file or directory
2023/07/19 (16:59:27) | DEBUG: Shared::init() : Initialized.
2023/07/19 (16:59:27) | DEBUG: Loading theme file: /usr/share/btop/themes/gruvbox_material_dark.theme
2023/07/19 (16:59:51) | INFO: Quitting! Runtime: 00:00:24
```

Nvidia GPU user here :)

**Comment by romner-set** [comment]
It's enabled by default, and based on the logs it seems to have initialized correctly. GPUs should show up in the CPU box if you have no config, and 5-0 keys should bring up the detailed panel. There's also a bunch of new graphs that you can set for the CPU panel in settings, numbered 12-17.

What GPU and driver version are you using? It could be too old for NVML to recognize it.

**Comment by nobounce** [comment]
NVIDIA GeForce RTX 3060
Driver: 535.86.05
Cuda: 12.2.0

**Comment by nobounce** [comment]
Removing the config file fixes this.
Please include `<sstream>` in btop_draw.cpp (for clang)
