### ISSUE TITLE
[ISSUE] Can't Install

### ISSUE THREAD

**Issue by TheDestr0yer** [romner-set/btop-gpu#4]
Hi i've this error when trying to install : 

ubuntudg@UbuntuDG:~/btop-gpu$ sudo make install
Installing binary to: /usr/local/bin/btop
cp: impossibile eseguire stat di 'bin/btop': File o directory non esistente
chmod: impossibile accedere a '/usr/local/bin/btop': File o directory non esistente
Installing doc to: /usr/local/share/btop
Installing themes to: /usr/local/share/btop/themes
Installing desktop entry to: /usr/local/share/applications/btop.desktop
cp: impossibile eseguire stat di 'btop.desktop': File o directory non esistente
Installing PNG icon to: /usr/local/share/icons/hicolor/48x48/apps/btop.png
Installing SVG icon to: /usr/local/share/icons/hicolor/scalable/apps/btop.svg

**Comment by romner-set** [comment]
You need to compile it first, i.e. `make && sudo make install`. GPU support has already been merged into btop though, so you might want to consider using the base repo instead.

**Comment by TheDestr0yer** [comment]
Hi , I actually solved a few moments after I opened the issue only not github does not allow deletion . Thanks anyway
